openapi: 3.0.0
info:
  title: Farmer E-Commerce API
  version: 1.0.0
  description: API documentation for the Farmer E-Commerce platform.
servers:
  - url: /api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths: {}
